# Logitech G810 LED Keyboard
groups:
    numeric:
        numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
        extras: [GRAVE, MINUS, EQUAL]
        functions-extra: [SYSRQ, SCROLLLOCK, PAUSE]

    alpha:
        upper:
            letters: [Q, W, E, R, T, Y, U, I, O, P]
            extra: [LBRACE, RBRACE]
        middle:
            letters: [A, S, D, F, G, H, J, K, L]
            extra: [SEMICOLON, APOSTROPHE, BACKSLASH]
        lower:
            letters: [Z, X, C, V, B, N, M]
            extra: [102ND, COMMA, DOT, SLASH]

    functions:
        f-keys: [F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12]
        extra: [ESC]

    modifiers: [LCTRL, RCTRL, LSHIFT, RSHIFT, LMETA, RMETA, LALT, RALT, CAPSLOCK, FN, COMPOSE, ENTER, BACKSPACE, TAB, SPACE]

    movement: [INSERT, DELETE, HOME, END, PAGEUP, PAGEDOWN]

    arrows: [LEFT, RIGHT, UP, DOWN]

    numpad: [KP0, KP1, KP2, KP3, KP4, KP5, KP6, KP7, KP8, KP9, NUMLOCK, KPSLASH, KPASTERISK, KPMINUS, KPPLUS, KPENTER, KPDOT]

    special:
        buttons: [GAME, LIGHT, MUTE, PLAY, STOP, PREV, NEXT]
        leds: [LOGO, NUMLOCKLED, CAPSLOCKLED, SCOLLLOCKLED]

effects:
    keyleds-default:
        plugins:
            - effect: fill
              color: ffffff
              special: ff0000
            - effect: feedback      # turn keys on when pressed
              color: ff0000         # color when just pressed
              sustain: 50           # how long (in milliseconds) the color is held
              decay: 500            # how long (in milliseconds) it then takes to fade out


profiles:
    __default__:                    # Special name __default__ is active when no other profile matches
        effect: keyleds-default     # Apply this effect
